plugins {
    id 'com.android.application'
}

android {
    namespace 'com.afrocom.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.afrocom.app"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix ".debug"
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.webkit:webkit:1.9.0'
    implementation 'com.google.android.material:material:1.11.0'
    // PDF viewer (affichage in-app sans dépendances lourdes)
    implementation 'com.github.barteksc:android-pdf-viewer:3.2.0-beta.1'
}
